export default crops = {
        rice:{image:require('../constants/rice.jpg'),price:'$11',URL:'https://www.amazon.com/s?k=rice+seeds&ref=nb_sb_noss_2'},
        maize:{image:require('../constants/corn.jpg'),URL:'https://www.amazon.com/s?k=maize+seeds&ref=nb_sb_noss',price:'$16'},
        chickpea:{image:require('../constants/chickpea.jpg'),URL:'https://www.amazon.com/s?k=chickpea+seeds&ref=nb_sb_noss',price:'$8'},
        kidneybeans:{image:require('../constants/kidney.jpg'),URL:'https://www.amazon.com/s?k=kidneybeans+seeds&ref=nb_sb_noss_2',price:'$16'},
        pigeonpeas:{image:require('../constants/pigeonPeas.jpg'),URL:'https://www.amazon.com/s?k=pigeon+peas+seeds&ref=nb_sb_noss_2',price:'$12'},
        mothbeans:{image:require('../constants/mothbeans.jpg'),URL:'https://www.amazon.com/s?k=mothbeans&ref=nb_sb_noss',price:'$17'},
        mungbean:{image:require('../constants/mungbean.jpg'),URL:'https://www.amazon.com/s?k=mungbean&ref=nb_sb_noss_2',price:'$11'},
        blackgram:{image:require('../constants/blackGram.jpg'),URL:'https://www.amazon.com/s?k=blackgram+seeds&ref=nb_sb_noss',price:'$15'},
        lentil:{image:require('../constants/lentil.jpg'),URL:'https://www.amazon.com/s?k=lentil&ref=nb_sb_noss_2',price:'$14'},
        pomegranate:{image:require('../constants/pomegranate.jpg'),price:'$3',URL:'https://www.amazon.in/s?k=pomegranate+seeds+buy&adgrpid=61755334747&ext_vrnc=hi&gclid=Cj0KCQjw_fiLBhDOARIsAF4khR2ayLWpr1kdWSzkqWoqFBAH0I_PtLiF0s_uNmXZIx9muWudb45aBgEaArPkEALw_wcB&hvadid=294126525036&hvdev=c&hvlocphy=1007823&hvnetw=g&hvqmt=e&hvrand=12207623934707142469&hvtargid=kwd-303700731531&hydadcr=8945_1781668&tag=googinhydr1-21&ref=pd_sl_2tncu4xdb6_e'},
        banana:{image:require('../constants/banana.jpg'),URL:'https://www.fast-growing-trees.com/collections/banana-trees',price:'$30'},
        mango:{image:require('../constants/mango.jpg'),URL:'https://www.fast-growing-trees.com/collections/shop?type=product&q=mango&undefined=undefined',price:'$110'},
        grapes:{image:require('../constants/grapes.jpg'),URL:'https://www.fast-growing-trees.com/collections/shop?type=product&q=grapes&undefined=undefined',price:'$28'} ,
        watermelon:{image:require('../constants/watermelon.jpg'),URL:'https://www.growjoy.com/store/pc/Watermelon-Plants-c64.htm',price:'$7'},
        muskmelon:{image:require('../constants/muskmelon.jpg'),URL:'https://www.trustbasket.com/collections/musk-melon-plant-seeds',price:'$30'},
        apple:{image:require('../constants/apple.jpg'),URL:'https://www.fast-growing-trees.com/collections/shop?type=product&q=apple&undefined=undefined',price:'$85'},
        orange:{image:require('../constants/orange.jpg'),URL:'https://www.fast-growing-trees.com/collections/shop?type=product&q=orange&undefined=undefined',price:'$48'},
        papaya:{image:require('../constants/papaya.jpg'),URL:'https://www.fast-growing-trees.com/collections/shop?type=product&q=papaya&undefined=undefined',price:'$75'},
        coconut:{image:require('../constants/coconut.jpg'),URL:'https://www.fast-growing-trees.com/collections/shop?type=product&q=coconut&undefined=undefined',price:'$70'},
        cotton:{image:require('../constants/cotton.jpg'),URL:'https://www.mrcseeds.com/buy-cotton-seeds-online/',price:'$11'}, 
        jute:{image:require('../constants/jute.jpg'),URL:'https://www.amazon.com/jute-seeds/s?k=jute+seeds',price:'$10'},
        coffee:{image:require('../constants/coffee.jpg'),URL:'https://www.fast-growing-trees.com/collections/shop?type=product&q=coffee&undefined=undefined',price:'$35'},
    }