export default  diseases = {
    bacterial_blight:{
        details:'Brown spots on the margins of the cotyledons characterize plants infected early in the growing season.Young plants may be stunted and if the infection reaches the growing point, they may die.Symptoms in later growth stages include angular lesions, which begin as small yellow to brown spots on the leaves.',
        symptoms:'The first symptoms seen with common bacterial blight are small water-soaked spots on the underside of leaves.The spots enlarge and coalesce becoming brown, dry, and brittle.A narrow yellow border surrounding lesions also characterizes these spots.Lesions may be found in both interveinal areas and along leaf margins.Affected pods develop circular, water-soaked areas that may also have yellow masses of bacteria observed on lesions.Later, spots on pods, and become reddish-brown and sunken.Early pod infection results in small, shriveled and discolored seed.',
        treatment:"Use seed that is blight tolerant, and certified to be disease-free.Don't spread old bean straw into fields to be planted with beans.Avoid walking into fields that are wet.Other cultural practices for management include avoiding the reuse of irrigation water, and incorporating infected debris after harvest and rotating out of beans with other crops for at least two years."
    },
    curl_virus:{
        details:'This virus is transmitted by an insect vector from the family Aleyrodidae and order Hemiptera, the whitefly Bemisia tabaci, commonly known as the silverleaf whitefly or the sweet potato whitefly.The primary host for TYLCV is the tomato plant, and other plant hosts where TYLCV infection has been found include eggplants, potatoes, tobacco, beans, and peppers.',
        symptoms:'The symptoms of leaf curl disease are very complex, and the typical symptoms include leaf curling, puckering of leaves, vein yellowing, stunting, excessive branching, from pale yellowing to deep yellowing, and smalling of leaves.Apart from this, it also causes the extreme distortion of leaves, stunting of plants, and premature drop of flower and fruits.At cellular level, structural changes have been observed like hypertrophy of nucleus and accumulation of dark granules and the aggregate of virus-like particles in the cytoplasm',
        treatment:'Crop rotation can be utilized for management of disease spread by naturally breaking the life cycles of insect vectors, disease, and weeds.Rotating to nonhost crops prevents the buildup of large populations of the insect vector and also establishes host-free periods.Careful monitoring of sequential plantings should be done for virus management.Avoid sowing of tomato close to already infected fields.Synchronized planting should be followed to avoid initial inoculum from tomato plants.'
    },
    fussarium_wilt:{
        details:'The fungal pathogen Fusarium oxysporum affects a wide variety of hosts of any age.Tomato, tobacco, legumes, cucurbits, sweet potatoes and banana are a few of the most susceptible plants, but it also infects other herbaceous plants.',
        symptoms:'Thrives at soil temperatures above 24 °C (75 °F) and can live indefinitely in soil without access to living host plants.Infected plants are usually stunted; their leaves turn pale green to golden yellow and later wilt, wither, die, and drop off progressively upward from the stem base.Dark streaks occur in the xylem vascular tissue of the roots and lower stem, and the roots may decay.',
        treatment:'The spread of the pathogen can be somewhat controlled by using clean seeds and removing infected plant tissues from the area, though the most effective management strategy is to plant resistant varieties.Depending on the forma specialis (host-specific form) responsible for a given infection, the disease can sometimes be controlled with soil fungicides, though some forms have developed resistance.Given its longevity, crop rotation is generally ineffective.'
    },
    healthy_corn:{
        details:'No diseases detected.',
        symptoms:'The Corn seems healthy.',
        treatment:'Relax no serious disease was found.'
    },
    healthy:{
        details:'No diseases detected.',
        symptoms:'It seems healthy.',
        treatment:'Relax no serious disease was found.'
    },
    diseased_okra_leaf:{
        details:'These spores adhere to the leaf surface and grow, becoming mycelia growth.This growth is present on the undersides of the leaves in the form of yellowing and brown spots.As the disease progresses, the leaves become dry and brown.Cercospora survives in plant residue left from hosts such as beet, spinach, eggplant, and, of course, okra.It is favored by warm, wet weather.The most serious outbreaks occur after a period of rainy weather.It is spread by wind, rain, and irrigation, as well as mechanical tool use.Read more at Gardening Know How: What Is Okra Leaf Spot: Tips For Treating Leaf Spot Of Okra https://www.gardeningknowhow.com/edible/vegetables/okra/treating-leaf-spot-on-okra.htm',
        symptoms:'Spots on okra leaves may also be the result of the pathogen Cercospora abelmoschi.Cercospora is a fungal infection wherein spores are carried by the wind from infected plants to other plants.These spores adhere to the leaf surface and grow, becoming mycelia growth.This growth is present on the undersides of the leaves in the form of yellowing and brown spots.As the disease progresses, the leaves become dry and brown.',
        treatment:'Keeping leaf wet for a long time is a major cause of infection primarily through water-splashed spores.Manage overhead irrigation with minimal chances of continued long periods of leaf wetness.If the problem is a continuous one, use protective fungicides before any infection can happen.Fungicide management may be difficult once the symptoms develop.'
    },
    fresh_okra_leaf:{
        details:'The leaf is fresh and disease free.',
        symptoms:'The Leaf seems healthy.',
        treatment:'Relax no serious disease was found.'
    },
    apple_apple_scrab:{
        details:'Apple scab is caused by the fungus Venturia inaequalis.It infects crabapples and apples (Malus spp.), mountain ash (Sorbus spp.), pear (Pyrus communis) and Cotoneaster (Cotoneaster spp.).The apple scab fungus has several host-specific strains that can cause disease on one type of plant but not any other.For example, the strain of V.inaequalis that infects mountain ash will only infect other mountain ash trees and will not infect crabapple trees.',
        symptoms:'Olive-green to black velvety spots with indistinct margins on leaves.Severe cases can lead to yellowing of the leaves and early defoliation.Olive-green to black lesions on the fruit turn brown and corky over time.,',
        treatment:'Remove and destroy the fallen leaf litter so that the fungus cannot overwinter.This may reduce the disease pressure in the following spring, but will not likely eliminate the disease.Do not overcrowd plants, and make sure the canopy has proper airflow.This will decrease the conditions favorable for disease development.Fungicide applications at 2-week intervals beginning when new growth is expanding in the spring.Crabapple cultivars that are resistant to apple scab are widely available.'
    },
    apple_black_rot:{
        details:'Large brown rotten areas can form anywhere on the fruit but are most common on the blossom end.The flesh of the apple is brown but remains firm.',
        symptoms:'They appear as small, purple specks on the upper surface of the leaves that enlarge into circular lesions 1/8 to 1/4 inch (3-6 mm) in diameter.        The margin of the lesions remains purple, while the center turns tan to brown.In a few weeks, secondary enlargement of these leaf spots occurs.        Heavily infected leaves become chlorotic and defoliation occurs.        As the rotted area enlarges, a series of concentric bands of uniform width form which alternate in color from black to brown.The flesh of the rotted area remains firm and leathery.Black pycnidia are often seen on the surface of the infected fruit.        Lesions resulting in canker formation usually are associated with a wound in the bark',
        treatment:'Prune out dead or diseased branches.Pick all dried and shriveled fruits remaining on the trees.Remove infected plant material from the area.All infected plant parts should be burned, buried or sent to a municipal composting site.Be sure to remove the stumps of any apple trees you cut down.'
    },
    apple_cedar_apple_rust:{
        details:'In early spring, during wet weather, these galls swell and bright orange masses of spores are blown by the wind where they infect susceptible apple and crab-apple trees.The spores that develop on these trees will only infect junipers the following year.From year to year, the disease must pass from junipers to apples to junipers again; it cannot spread between apple trees.',
        symptoms:'Leaf spots are first yellow then turn bright orange-red, often with a bright red border.Small, raised, black dots form in the center of leaf spots on the upper leaf surface when the leaf spots mature.Very short (less than 1/10th inch), finger-like fungal tubes stick out from the lower surface of the leaf, directly below leaf spots. The fungal tubes appear fringed when they open at the tip to release yellow to orange, powdery spores.Rarely, green to brown irregular spots with black dots form on the fruit surface.Fruit spots do not extend deep into the fruit.',
        treatment:'Choose resistant cultivars when available.Rake up and dispose of fallen leaves and other debris from under trees.Remove galls from infected junipers.In some cases, juniper plants should be removed entirely.Apply preventative, disease-fighting fungicides labeled for use on apples weekly, starting with bud break, to protect trees from spores being released by the juniper host.This occurs only once per year, so additional applications after this springtime spread are not necessary.On juniper, rust can be controlled by spraying plants with a copper solution (0.5 to 2.0 oz/ gallon of water) at least four times between late August and late October.Safely treat most fungal and bacterial diseases with SERENADE Garden.This broad spectrum bio-fungicide uses a patented strain of Bacillus subtilis that is registered for organic use.Best of all, SERENADE is completely non-toxic to honey bees and beneficial insects.    Containing sulfur and pyrethrins, Bonide® Orchard Spray is a safe, one-hit concentrate for insect attacks and fungal problems.For best results, apply as a protective spray (2.5 oz/ gallon) early in the season.If disease, insects or wet weather are present, mix 5 oz in one gallon of water.Thoroughly spray all parts of the plant, especially new shoots.Contact your local Agricultural Extension office for other possible solutions in your area.'
    },
    apple_healthy:{
        details:'The apple is healthy and it can be used to eat',
        symptoms:'The crop seems healthy.',
        treatment:'Relax no serious disease was found.'
    },
    blueberry_healthy:{
        details:'The blueberry is healthy and it can be used to eat',
        symptoms:'The crop seems healthy.',
        treatment:'Relax no serious disease was found.'
    },
    cherry_including_sour_healthy :{
        details:'Cause Podosphaera cerasi (formerly P-clandestina), a fungus that most commonly infects young, expanding leaves but can also be found on buds, fruit and fruit stems.It overwinters as small, round, black bodies (chasmothecia) on dead leaves, on the orchard floor, or in tree crotches.Some chasmothecia may be trapped in bark crevices.In spring as buds break, irrigation or rain releases ascospores and wind spreads them to young leaves.When the right combination of temperature and leaf wetness duration occurs, these ascospores start the first colonies of the season',
        symptoms:'The crop seems healthy.',
        treatment:'Relax no serious disease was found.'
    },
    cherry_including_sour_powdery_mildew:{
        details:'Sour cherry (Prunus cerasus), also commonly called tart cherry, is a fruit.The Montmorency sour cherry is the most popular type grown in the U.S.Sour cherry fruit contains chemicals that might reduce swelling and act as antioxidants.Some sour cherry products are marketed for specific health purposes, but up to 97% of sour cherries grown are used in cooking and baking.',
        symptoms:'Symptoms usually appear later in the growing season on outdoor plants.Powdery mildew starts on young leaves as raised blister-like areas that cause leaves to curl, exposing the lower leaf surface.Infected leaves become covered with a white to gray powdery growth, usually on the upper surface; unopened flower buds may be white with mildew and may never open.Leaves of severely infected plants turn brown and drop.The disease prefers young, succulent growth; mature leaves are usually not affected.',
        treatment:'Plant resistant cultivars in sunny locations whenever possible.Prune or stake plants to improve air circulation.Make sure to disinfect your pruning tools (one part bleach to 4 parts water) after each cut.Remove diseased foliage from the plant and clean up fallen debris on the ground.Use a thick layer of mulch or organic compost to cover the soil after you have raked and cleaned it well.Mulch will prevent the disease spores from splashing back up onto the leaves.Milk sprays, made with 40% milk and 60% water, are an effective home remedy for use on a wide range of plants.For best results, spray plant leaves as a preventative measure every 10-14 days.Wash foliage occasionally to disrupt the daily spore-releasing cycle.Neem oil and PM Wash, used on a 7 day schedule, will prevent fungal attack on plants grown indoors.Water in the morning, so plants have a chance to dry during the day.Drip irrigation and soaker hoses will help keep the foliage dry.Use a slow-release, organic fertilizer on crops and avoid excess nitrogen.Soft, leafy, new growth is most susceptible.Destroy all plant debris after harvest (see Fall Garden Cleanup).Do NOT compost'
    },
    corn_maize_cercospora_leaf_spot_gray_leaf_spot:{
        details:'Gray leaf spot (GLS) is a common fungal disease in the United States caused by the pathogen Cercospora zeae-maydis in corn.Disease development is favored by warm temperatures, 80°F or 27 °C; and high humidity, relative humidity of 90% or higher for 12 hours or more.Cercospora zeae-maydis overwinters in corn residue, allowing inoculum to build up from year to year in fields.',
        symptoms:'The disease first appears in the form of small, necrotic spots with halos.These usually expand to become rectangular lesions, about 1/8 inch wide by up to 2 inches to 3 inches long and gray to brown in appearance.Mature lesions usually have distinct parallel edges and appear opaque when put up to the light, but the lesions hybrids vary widely in shape and color.Symptoms can sometimes be confused with northern corn leaf spot, although gray leaf spot lesions are usually limited on the sides by veins.',
        treatment:'Disease management tactics include using resistant corn hybrids, conventional tillage where appropriate, and crop rotation.Foliar fungicides can be effective if economically warranted.Typically they are only profitable on susceptible inbreds or susceptible hybrids under a combination of high risk conditions with high yield potential, prolonged humid conditions, and evidence of disease development.'
    },
    corn_maize_common_rust_:{
        details:'The common rust fungus overwinters in the southern U.S.and Mexico.Urediniospores are blown north to the Midwestern Corn Belt in the summer and infection occurs in June or July.Young leaves are most susceptible to infection and pustules are more likely to form after corn silking.The disease favors cool temperatures (60 - 76 degrees F), heavy dews, about six hours of leaf wetness, and relative humidity greater than 95 percent.',
        symptoms:'Common rust produces rust-colored to dark brown, elongated pustules on both leaf surfaces.The pustules contain rust spores (urediniospores) that are cinnamon brown in color.Pustules darken as they age.Leaves, as well as sheaths, can be infected.Under severe conditions leaf chlorosis and death may occur.Common rust can be differentiated from Southern rust by the brown pustules occurring on both top and bottom leaf surfaces with common rust',
        treatment:'The best management practice is to use resistant corn hybrids.Fungicides can also be beneficial, especially if applied early when few pustules have appeared on the leaves.'
    },
    infected:{
        details:'Lesions can eventually expand to a more oblong or “cigar” shape.They may also coalesce to form large areas of necrotic tissue.There are several host-specific forms of E.turcicum.The most economically important host is corn, but other forms may infect sorghum, Johnson grass, or sudangrass.',
        symptoms:'The most common diagnostic symptom of the disease on corn is cigar-shaped or elliptical necrotic gray-green lesions on the leaves that range from one to seven inches long.',
        treatment:'The best management practice is to use resistant corn hybrids.Fungicides can also be beneficial, especially if applied early when few pustules have appeared on the leaves.'
    },
    corn_maize_northern_leaf_blight:{
        details:'Lesions can eventually expand to a more oblong or “cigar” shape.They may also coalesce to form large areas of necrotic tissue.There are several host-specific forms of E.turcicum.The most economically important host is corn, but other forms may infect sorghum, Johnson grass, or sudangrass.The most common diagnostic symptom of the disease on corn is cigar-shaped or elliptical necrotic gray-green lesions on the leaves that range from one to seven inches long.',
        symptoms:"Typical symptoms of northern corn leaf blight are canoe-shaped lesions 1 inch to 6 inches long.The lesions are initially bordered by gray-green margins.They eventually turn tan colored and may contain dark areas of fungal sporulation.The length or size of lesions may vary with in different corn hybrids reactions with different resistance genes.Lesions begin on the lower leaves and then spread to upper leaves.Severe symptoms can progress rapidly, resulting in blighted leaves.The disease can be confused with symptoms of Goss's leaf blight on some hybrids, and perhaps with Stewarts wilt where this disease occurs.",
        treatment:'Use resistant hybrids.Fungicides may be warranted on inbreds for seed production during the early stages of this disease.Crop rotation and tillage practices may be helpful in some cases.'
    },
    corn_maize_healthy:{
        details:'The corn maize is healthy.',
        symptoms:'The crop seems healthy.',
        treatment:'Relax no serious disease was found.'
    },
    grape_black_rot:{
        details:'Disease development is favored by warm and humid weather.Symptoms of black rot first appear as small yellow spots on leaves.Enlarged spots (lesions) have a dark brownish-red border with tan to dark brown centers.All cultivated varieties (American, French Hybrid or vinifera) of grapes are susceptible to infection by the black rot fungus.However, over the growing season, berries become resistant to black rot infections.',
        symptoms:'The disease attacks the leaves, stem, flowers and berries.All the new growth on the vineis prone to attack during the growing season.The symptoms are in the form of irregularly shapedreddish brown spots on the leaves and a black scab on berries.Occasionally, small elliptical darkcoloured canker lesions occur on the young stems and tendrils.Leaf, cane and tendril infection canoccur only when the tissue is young, but berries can be infected until almost fully-grown if an activefungicide residue is not present.The affected berries shrivel and become hard black mummies.',
        treatment:'Use protective fungicide sprays.Pesticides registered to protect the developing new growth include copper, captan, ferbam, mancozeb, maneb, triadimefon, and ziram.Important spraying times are as new shoots are 2 to 4 inches long, and again when they are 10 to 15 inches long, just before bloom, just after bloom, and when the fruit has set.'
    },
    grape_esca_black_measles:{
        details:'Grapevine measles, also called esca, black measles or Spanish measles, has long plagued grape growers with its cryptic expression of symptoms and, for a long time, a lack of identifiable causal organism(s).The name ‘measles’ refers to the superficial spots found on the fruit.',
        symptoms:'Symptoms are characterized by a ‘tiger stripe’ pattern when infections are severe from year to year.Mild infections can produce leaf symptoms that can be confused with other diseases or nutritional deficiencies.White cultivars will display areas of chlorosis followed by necrosis, while red cultivars are characterized by red areas followed by necrosis.Early spring symptoms include shoot tip dieback, leaf discoloration and complete defoliation in severe cases.',
        treatment:'Strict sanitation and protection of all wounds from pruning to grafting will help protect vines during nursery production.Frequently disinfest pruning shears, hydration tanks, grafting machines, and callusing rooms.Grow mother vines in well-drained soil or raised beds.Use drip irrigation that does not over-wet the root crown.Immediately after grafting, nurseries should dip vines into specialized waxes containing plant growth regulators or fungicide-impregnated formulations, which encourage graft union callus development while inhibiting fungal contamination.Soak dormant cuttings 30 min.in hot water (122°F or 50°C).This has not always been effective and must be combined with other methods.Delay fruiting for several years until vines have balanced root and shoot growth.Cropping several tons in the second year after planting has been associated with these diseases When making large cuts during wet weather, leave a stub several inches long to be pruned off later during dry weather.Sometimes referred to as delayed or double pruning or prepruning.Remove prunings from the vineyard.Pruning wound treatments with sealants or paints have been effective when used within 24 hours of the pruning cut.These products include B-Lock, Spur Shield, or Vitiseal.See labels for details.'
    },
    grape_leaf_blight_isariopsis_leaf_spot:{
        details:'Scattered, somewhat angular, purple-brown spots on upper leaf surface.Corresponding, less conspicuous, brown spots on lower leaf surface.Corresponding, less conspicuous, brown spots on lower leaf surface.Numerous scattered, somewhat angular, purple-brown spots on upper leaf surface.Numerous scattered, somewhat angular, purple-brown spots on',
        symptoms:'The yellow-green disease spots gradually appear on the fronts of the grape leaves with downy mildew, and white frosty mildew appears on the backs of the leaves.Leaf blight produces dark brown patches on the surface of grape leaves.',
        treatment:'Spraying of the grapevines at 3-4 leaf stage with fungicides like Bordeaux mixture @ 0.8% or Copper Oxychloride @ 0.25% or Carbendazim @ 0.1% are effective against this disease.'
    },
    grape_healthy:{
        details:'The grape is healthy and disease free.',
        symptoms:'The crop seems healthy.',
        treatment:'Relax no serious disease was found.'
    },
    orange_haunglongbing_citrus_greening:{
        details:'Huanglongbing (HLB) or citrus greening is the most severe citrus disease, currently devastating the citrus industry worldwide.The presumed causal bacterial agent Candidatus Liberibacter spp.affects tree health as well as fruit development, ripening and quality of citrus fruits and juice.Fruit from infected orange trees can be either symptomatic or asymptomatic.Symptomatic oranges are small, asymmetrical and greener than healthy fruit.Furthermore, symptomatic oranges show higher titratable acidity and lower soluble solids, solids/acids ratio, total sugars, and malic acid levels.',
        symptoms:'Visible psyllids or waxy psyllid droppings.Lopsided, bitter, hard fruit with small, dark aborted seeds.Fruit that remains green even when ripe.Asymmetrical blotchy mottling of leaves.Yellow shoots.Twig dieback.Stunted, sparsely foliated trees that may bloom off season.',
        treatment:'Advanced Nutritional Supplements.To slow the progression of citrus greening in infected trees, trace amounts of nutrients are applied to the leaves or to the roots. Reflective Mulch can be used  Heat Treatment reduces the psyllid count, which can potentially prolong the productivity of trees Use of Bactericides and Citrus Under Protective Screen (CUPS)'
    },
    peach_bacterial_spot:{
        details:'Bacterial spot is an important disease of peaches, nectarines, apricots, and plums caused by Xanthomonas campestris pv.pruni.Symptoms of this disease include fruit spots, leaf spots, and twig cankers.Fruit symptoms include pitting, cracking, gumming, and watersoaked tissue, which can make the fruit more susceptible to brown rot, rhizopus, and other fungal infections.',
        symptoms:'The most characteristic sign of peach tree leaf spot are angular purple to purple-brown spots on foliage, followed by the center of lesion falling out, giving the leaves a “shot hole” appearance.Leaves soon turn yellow and drop.',
        treatment:'Compounds available for use on peach and nectarine for bacterial spot include copper, oxytetracycline (Mycoshield and generic equivalents), and syllit+captan; however, repeated applications are typically necessary for even minimal disease control.'
    },
    peach_healthy:{
        details:'The peach is healthy.',
        symptoms:'The crop seems healthy.',
        treatment:'Relax no serious disease was found.'
    },
    pepper_bell_bacterial_spot:{
        details:'Bacterial spot develops most rapidly during periods of warm temperatures and prolonged wet conditions.The pathogen survives in and on seeds and in plant debris (McGrath & Boucher, 2012).Although persistence of debris and the pathogen depend on environmental conditions, it is very common for the pathogen to survive in debris for at least a year.However, once infected debris gets decomposed and the organism is exposed to soil, it cannot stay alive for more than a few weeks.Infected weeds and volunteer host plants also can be sources of inoculum.',
        symptoms:'Symptoms begin as small, yellow-green lesions on young leaves which usually appear deformed and twisted , or as dark, water soaked, greasy-appearing lesions on older foliage .Lesions develop rapidly to a size of 0.25 to 0.5 cm (0.1 to 0.2 in.) wide and become tan to brownish-red.lesions may form on fruit, including the peduncle .',
        treatment:'Seed treatment with sodium hypochlorite (for example, Clorox) is effective in reducing bacterial populations on seed surfaces.Seed treatment with hot water is effective in reducing bacterial populations on the surface and inside the seeds.However, seed germination may be affected by heat treatment if not done accurately, while the risk is relatively low with bleach treatment.'
    },
    pepper_bell_healthy:{
        details:'The pepper bell is healthy and disease free.',
        symptoms:'The crop seems healthy.',
        treatment:'Relax no serious disease was found.'
    },
    potato_early_blight:{
        details:'Early blight of potato is a common disease found in most potato growing regions.The disease is caused by the fungus Alternaria solani, which can also afflict tomatoes and other members of the potato family.Potatoes become infected with early blight when foliage has become excessively wet due to rain, fog, dew, or irrigation.Although not a terminal disease, severe infections can be fairly detrimental.In contrast to its name, early blight rarely develops early; it actually usually affects mature foliage rather than young, tender leaves.Read more at Gardening Know How: Potato Early Blight Treatment – Managing Potatoes With Early Blight https://www.gardeningknowhow.com/edible/vegetables/potato/potato-early-blight-treatment.htm',
        symptoms:'The first symptoms of early blight appear as small, circular or irregular, dark-brown to black spots on the older (lower) leaves .These spots enlarge up to 3/8 inch in diameter and gradually may become angular-shaped.Multiple lesions on the same leaf also may coalesce, or grow together, to form one mass As lesions coalesce, chlorosis (yellowing of plant tissue) may be visible due to clusters of infection',
        treatment:'Treatment of early blight includes prevention by planting potato varieties that are resistant to the disease; late maturing are more resistant than early maturing varieties.Avoid overhead irrigation and allow for sufficient aeration between plants to allow the foliage to dry as quickly as possible Practice a 2-year crop rotation.Remove plant debris and weed hosts at the end of the season to mitigate areas where the disease may overwinter.'
    },
    potato_late_blight:{
        details:'The first symptoms of late blight in the field are small, light to dark green, circular to irregular-shaped water-soaked spots .These lesions usually appear first on the lower leaves.Lesions often begin to develop near the leaf tips or edges, where dew is retained the longest.',
        symptoms:'The first symptoms of late blight in the field are small, light to dark green, circular to irregular-shaped water-soaked spots .These lesions usually appear first on the lower leaves.Lesions often begin to develop near the leaf tips or edges, where dew is retained the longest.',
        treatment:' Late blight is controlled by eliminating cull piles and volunteer potatoes, using proper harvesting and storage practices, and applying fungicides when necessary.Air drainage to facilitate the drying of foliage each day is important.'
    },
    potato_healthy:{
        details:'The potato is healthy.',
        symptoms:'The crop seems healthy.',
        treatment:'Relax no serious disease was found.'
    },
    raspberry_healthy:{
        details:'The raspberry is healthy',
        symptoms:'The crop seems healthy.',
        treatment:'Relax no serious disease was found.'
    },
    soybean_healthy:{
        details:'The soybean is healthy',
        symptoms:'The crop seems healthy.',
        treatment:'Relax no serious disease was found.'
    },
    squash_powdery_mildew:{
        details:'White deposits develop on the top sides of leaves that make them look like they have been dusted with flour.As this fungal disease advances, leaves become grayish-green and become dry to the touch.Eventually these leaves turn brown and fall off.Powdery mildew is most likely to infect older plants that are beginning to decline after producing a crop.Warm temperatures between 70 and 80F (21 to 27C) favor cucurbit powdery mildew, but rainy weather is not required to trigger an outbreak.',
        symptoms:'Symptoms usually appear later in the growing season on outdoor plants.Powdery mildew starts on young leaves as raised blister-like areas that cause leaves to curl, exposing the lower leaf surface.Infected leaves become covered with a white to gray powdery growth, usually on the upper surface; unopened flower buds may be white with mildew and may never open.Leaves of severely infected plants turn brown and drop.The disease prefers young, succulent growth; mature leaves are usually not affected.',
        treatment:'Plant resistant cultivars in sunny locations whenever possible.Prune or stake plants to improve air circulation.Make sure to disinfect your pruning tools (one part bleach to 4 parts water) after each cut.Remove diseased foliage from the plant and clean up fallen debris on the ground.Use a thick layer of mulch or organic compost to cover the soil after you have raked and cleaned it well.Mulch will prevent the disease spores from splashing back up onto the leaves.Milk sprays, made with 40% milk and 60% water, are an effective home remedy for use on a wide range of plants.For best results, spray plant leaves as a preventative measure every 10-14 days.Wash foliage occasionally to disrupt the daily spore-releasing cycle.Neem oil and PM Wash, used on a 7 day schedule, will prevent fungal attack on plants grown indoors.Water in the morning, so plants have a chance to dry during the day.Drip irrigation and soaker hoses will help keep the foliage dry.Use a slow-release, organic fertilizer on crops and avoid excess nitrogen.Soft, leafy, new growth is most susceptible.Destroy all plant debris after harvest (see Fall Garden Cleanup).Do NOT compost'
    },
    strawberry_leaf_scorch:{
        details:'Diplocarpon earlianum is a species of fungus that causes disease in strawberry plants called strawberry leaf scorch.The disease overwinters in plant debris and infects strawberry plants during the spring season when it is wet.The five main methods to reduce strawberry leaf scorch include: irrigation techniques, crop rotation, planting resistant and disease-free seeds, fungicide use, and sanitation measures.Control of strawberry leaf scorch is important because it is responsible for the majority of disease in strawberries.Diplocarpon earliana affects the fruit quality and yield of the strawberry crop',
        symptoms:'Strawberries with leaf scorch may first show signs of issue with the development of small purplish blemishes that occur on the topside of leaves.Over time, the spots will continue to grow larger and darken.In severe cases, dark spots may even cover entire portions of strawberry plant leaves and cause them to completely dry and fall from the plant.',
        treatment:'Using practices like crop rotation (for intervals of three to five years) Use of fungicides like Thiphanate-methyl Planting resistant and disease-free seed as well as burning all plant debris after harvest are some of the common sanitation methods that are used.'
    },
    strawberry_healthy:{
        details:'The strawberry is healthy',
        symptoms:'The crop seems healthy.',
        treatment:'Relax no serious disease was found.'
    },
    tomato_bacterial_spot:{
        details:'Three bacterial diseases are common in Ontario tomato fields: bacterial spot, caused by Xanthomonas campestris pv.vesicatoria; bacterial speck, caused by Pseudomonas syringae pv.tomato; and bacterial canker, caused by Clavibacter michiganensis subsp.michiganensis.In Ontario, bacterial disease is present at some level every season, though not always at destructive levels.However, when conditions are optimal for bacterial disease, losses in marketable yield can be up to 60% in some fields.',
        symptoms:'Bacterial spot appears on leaves as small (less than ⅛ inch), sometimes water-soaked (i.e., wet-looking) circular areas.Spots may initially be yellow-green, but darken to brownish-red as they age.When the disease is severe, extensive leaf yellowing and leaf loss can also occur.',
        treatment:'Soak seeds in a 20 percent bleach solution for 30 minutes (this may reduce germination) Soak seeds in water that is 125 F.(52 C.) for 20 minutes.When harvesting seeds, allow the seeds to ferment in the tomato pulp for one week.' 
    },
    tomato_early_blight:{
        details:'The most common cause of dark spots on tomato leaves, early blight begins on the oldest leaves closest to the ground.The irregularly-shaped spots have concentric rings around their edges, sometimes with a dark dot in the center.Affected leaves gradually wither to brown and hang on the stems, while leaves higher up on the plant remain green and healthy.Early blight spreads fastest in humid weather when temperatures are between 80 and 85F (27-29C).',
        symptoms:'Leaf spots are round, brown and can grow up to half inch in diameter.Larger spots have target-like concentric rings.The tissue around spots often turns yellow.Severely infected leaves turn brown and fall off, or dead, dried leaves may cling to the stem.',
        treatment:'Tomatoes that have early blight require immediate attention before the disease takes over the plants.Thoroughly spray the plant (bottoms of leaves also) with Bonide Liquid Copper Fungicide concentrate or Bonide Tomato & Vegetable.Both of these treatments are organic.'
    },
    tomato_late_blight:{
        details:'The first symptoms of late blight on tomato leaves are irregularly shaped, water-soaked lesions, often with a lighter halo or ring around them these lesions are typically found on the younger, more succulent leaves in the top portion of the plant canopy.During high humidity, white cottony growth may be visible on underside of the leaf , where sporangia form Spots are visible on both sides of the leaves.As the disease progresses, lesions enlarge causing leaves to brown, shrivel and die.',
        symptoms:'Firm, dark brown, circular spots grow to cover large parts of fruits.Spots may become mushy as secondary bacteria invade.In high humidity, thin powdery white fungal growth appears on infected leaves, fruit and stems.In cool, wet weather, entire fields turn brown and wilted as if hit by frost.',
        treatment:'Fungicides that contain maneb, mancozeb, chlorothanolil, or fixed copper can help protect plants from late tomato blight.Repeated applications are necessary throughout the growing season as the disease can strike at any time'
    },
    tomato_leaf_mold:{
        details:'The oldest leaves are infected first.Pale greenish-yellow spots, usually less than 1/4 inch, with no definite margins, form on the upper sides of leaves.Olive-green to brown velvety mold forms on the lower leaf surface below leaf spots.Leaf spots grow together and turn brown.Leaves wither and die but often remain attached to the plant.',
        symptoms:'The symptoms of this disease commonly occurs on foliage, and it develops on both sides of the leaf on the adaxial and abaxial surface.The older leaves are infected first and then the disease moves up towards young leaves.The diagnostic symptom develops on lower surface as an olive green to grayish purple and velvety appearance, which are composed of spores (conidia).Continuously, the color of the infected leaf changes to yellowish brown and the leaf begins to curl and dry.',
        treatment:"Sanitize the farmland between crop seasons.Use fans and avoid overhead watering to minimize leaf wetness.Also, stake and prune plants to increase ventilation.If the disease is detected, apply a fungicide according to the manufacturer's instructions at the first sign of infection."
    },
    tomato_septoria_leaf_spot:{
        details:'At this time of year, symptoms of Septoria leaf spot are quite evident on tomato leaves.This disease usually appears on lower mature leaves, causing them to turn yellow then brown and wither.Diseased leaves show small circular spots (lesions) with black or brown margins.The center of these lesions eventually turns gray, with small black fungal fruiting structures (pycnidia) scattered throughout.Lesions may also occur on stems and petioles, but tend to be more elongated.',
        symptoms:'A diagnostic feature of this disease is the presence of many dark-brown, pimple-like structures called pycnidia (fruiting bodies of the fungus) that are readily visible in the tan centers of the spots.When spots are numerous, affected leaves turn yellow and eventually shrivel up, brown, and drop off.',
        treatment:'Removing infected leaves.Remove infected leaves immediately, and be sure to wash your hands and pruners thoroughly before working with uninfected plants.Using organic fungicides containing either copper or potassium bicarbonate will help prevent the spreading of the disease.Consider using the chemical fungicide chlorothalonil.It is one of the least toxic and most effective and is sold under the names Fungonil and Daconil.'
    },
    tomato_spider_mites_two_spotted_spider_mite:{
        details:'The two-spotted spider mite is the most common mite species that attacks vegetable and fruit crops in New England.Spider mites can occur in tomato, eggplant, potato, vine crops such as melons, cucumbers, and other crops.Two-spotted spider mites are one of the most important pests of eggplant.They have up to 20 generations per year and are favored by excess nitrogen and dry and dusty conditions.Outbreaks are often caused by the use of broad-spectrum insecticides which interfere with the numerous natural enemies that help to manage mite populations.As with most pests, catching the problem early will mean easier control.',
        symptoms:'The tomato red spider mites are pale-orange to red and feed on the underside of leaves.They cannot be seen easily with the naked eye.Feeding damage caused by sucking sap appears as many shiny pale yellow marks on the top of the tomato leaf (see lower photo).Eventually the leaves turn brown and die or fall off.',
        treatment:'Use fungicides with sulphur, since they reduce populations of mites.You can also use miticides which are specific for mites e.g.Dynamec (active ingredient abamectin), Oberon (spiromesifen) or Omite (propargite).'
    },
    tomato_target_spot:{
        details:'arget spot symptoms begin as small dark lesions which enlarges to form light brown lesions with concentric pattern and a yellow halo around it in the transplants.Lesions can be seen inside the canopy and the micro-climate favors the infection process.The lesions on infected plants can become very large and cover significant area of the leaf in the field.Fruit lesions while starts as small lesions can enlarges to form large lesions with cracked centers (X) in the field or in ripening stage or shipment that can lead to post-harvest fruit rotting.',
        symptoms:"The disease starts on the older leaves and spreads upwards.The first signs are irregular-shaped spots (less than 1 mm) with a yellow margin.Some of the spots enlarge up to 10 mm and show characteristics rings, hence the name of  'target spot' .Spread to all leaflets and to other leaves is rapid , causing the leaves to turn yellow, collapse and die.",
        treatment:'Remove old plant debris at the end of the growing season; otherwise, the spores will travel from debris to newly planted tomatoes in the following growing season, thus beginning the disease anew.Rotate crops and don’t plant tomatoes in areas where other disease-prone plants have been located in the past year– primarily eggplant, peppers, potatoes or, of course– tomatoes.Water tomato plants in the morning so the leaves have time to dry.Water at the base of the plant or use a soaker hose or drip system to keep the leaves dry.'
    },
    tomato_tomato_yellow_leaf_curl_virus:{
        details:'Tomato yellow leaf curl virus is not seed-borne.It is only transmitted by the whitefly, Bemisia tabaci, which is commonly found in tropical and sub-tropical regions, and in greenhouses in temperate areas.Plants become severely stunted and shoots become erect.Leaflets are reduced in size and pucker.Leaflets curl upwards, become distorted, and have prominent yellowing along margins and/or interveinal regions.Flowers wither.',
        symptoms:'If plants are infected early, they may appear yellow and stunted overall.Mottled light and dark green on leaves.Leaves may be curled, malformed, or reduced in size.Spots of dead leaf tissue may become apparent with certain varieties at warm temperatures.',
        treatment:'Inspect plants for whitefly infestations two times per week.If whiteflies are beginning to appear, spray with azadirachtin (Neem), pyrethrin or insecticidal soap.For more effective control, it is recommended that at least two of the above insecticides be rotated at each spraying.'
    },
    tomato_tomato_mosaic_virus:{
        details:'If plants are infected early, they may appear yellow and stunted overall.Mottled light and dark green on leaves. Leaves may be curled, malformed, or reduced in size. Spots of dead leaf tissue may become apparent with certain varieties at warm temperatures.',
        symptoms:'Tomato Yellow Leaf Curl Virus caused a range of symptoms that include marginal leaf yellowing, upward or downward leaf cupping, reduction in leaf size, flower and/or fruit drop, and plant stunting.',
        treatment:'Plant resistant varieties when available or purchase transplants from a reputable source.Fungicides will not treat this viral disease.Do not save seed from infected crops.Avoid using tobacco around susceptible plants.Cigarettes and other tobacco products may be infected and can spread the virus.Avoid working in the garden during damp conditions (viruses are easily spread when plants are wet).Remove all perennial weeds, using least-toxic herbicides, within 100 yards of your garden plot.'
    },
    tomato_healthy:{
        details:'The tomato is healthy and disease free',
        symptoms:'The crop seems healthy.',
        treatment:'Relax no serious disease was found.'
    },
    tungro:{
        details:'Rice tungro disease is caused by the combination of two viruses, which are transmitted by leafhoppers.It causes leaf discoloration, stunted growth, reduced tiller numbers and sterile or partly filled grains.Tungro infects cultivated rice, some wild rice relatives and other grassy weeds commonly found in rice paddies.',
        symptoms:'Plants affected by tungro exhibit stunting and reduced tillering.Their leaves become yellow or orange-yellow, may also have rust-colored spots.Discoloration begins from leaf tip and extends down to the blade or the lower leaf portion.Most panicles sterile or partially filled grains',
        treatment:'Light traps are to be set up to attract and control the leaf hopper vectors as well as to monitor the population.In the early morning, the population of leafhopper alighting near the light trap should be killed by spraying/dusting the insecticides.This should be practiced every day.'
    },
    brownspot:{
        details:'Cochliobolus miyabeanus (formerly known as Helminthosporium oryzae) is a fungus that causes brown spot disease in rice.This disease was the causal agent of the Bengal famine of 1943.',
        symptoms:'Infected seedlings have small, circular, yellow brown or brown lesions that may girdle the coleoptile and distort primary and secondary leaves.Starting at tillering stage, lesions can be observed on the leaves.They are initially small, circular, and dark brown to purple-brown.Fully developed lesions are circular to oval with a light brown to gray center, surrounded by a reddish brown margin caused by the toxin produced by the fungi.',
        treatment:'Use resistant varieties.Contact your local agriculture office for up-to-date lists of varieties available.Use fungicides (e.g., iprodione, propiconazole, azoxystrobin, trifloxystrobin, and carbendazim) as seed treatments.Treat seeds with hot water (53−54°C) for 10−12 minutes before planting, to control primary infection at the seedling stage.To increase effectiveness of treatment, pre-soak seeds in cold water for eight hours.'
    },
    blast:{
        details:'Blast is caused by the fungus Magnaporthe oryzae.It can affect all above ground parts of a rice plant: leaf, collar, node, neck, parts of panicle, and sometimes leaf sheath.',
        symptoms:'Blast symptoms can occur on leaves, leaf collars, nodes and panicles.Leaf spots are typically elliptical (football shaped), with gray-white centers and brown to red-brown margins (Figure 1).Fully developed leaf lesions are approximately 0.4 to 0.7 inch long and 0.1 to 0.2 inch wide. Both the shape and the color vary depending on the environment, age of the lesion and rice variety.Lesions on leaf sheaths, which rarely develop, resemble those on leaves.The stems often break at the diseased node.',
        treatment:'Incorporate or roll the rice stubble soon after harvest to promote early decomposition.Plant the least-susceptible varieties and use a broad-spectrum seed treatment.Seed over a range of time to spread the heading dates.However, avoid planting late because blast will be more severe.Apply fungicides during the time frame predicted by the DD50 program, which is about 5 to 7 days before heading (late boot stage).'
    },
    bacterialblight:{
        details:'Rice bacterial blight, also called bacterial blight of rice, deadly bacterial disease that is among the most destructive afflictions of cultivated rice (Oryza sativa and O.glaberrima).In severe epidemics, crop loss may be as high as 75 percent, and millions of hectares of rice are infected annually.',
        symptoms:'Symptoms of common bacterial blight first appear on leaves as small, water-soaked spots, light green areas, or both.As these spots enlarge, the tissue in the center dies and turns brown.These irregularly shaped spots are bordered by a lemon yellow ring, which serves as a diagnostic symptom of common bacterial blight.The spots or lesions develop on the edges or interveinal areas of leaves.The spots may grow together, resulting in the death of the entire leaf and defoliation of the plant.Infected pods will have small, water-soaked spots that develop into large, dark red irregular spots, sometimes with a yellow slimy ooze.',
        treatment:'Avoid the use of sprinkler irrigation, especially for seed crop production, since sprinklers can provide the needed moisture and humidity for common bacterial blight to develop in California.In fields that have had common bacterial blight problems, deep plow infested bean debris and practice a 2- to 3-year rotation with a non-legume crop.There are no commercially available resistant varieties, although some tolerant varieties are available (e.g., Great Northern Harris).Pesticide sprays are generally not effective for controlling common bacterial blight.'
    },
    leaf_rust:{
        details:'Wheat leaf rust is a fungal disease that affects wheat, barley, rye stems, leaves and grains.In temperate zones it is destructive on winter wheat because the pathogen overwinters.Infections can lead up to 20% yield loss, which is exacerbated by dying leaves, which fertilize the fungus',
        symptoms:'Leaf rust is generally found on the leaves, but occasionally is found on glumes and awns.Symptoms are circular or oval, orange pustules on the upper surface of infected leaves.The spores within these pustules are easily dislodged and cover hands and clothing with an orange dust.As the wheat ripens, this orange stage turns into a new stage of the fungus, which is black, and often a mixture or orange and black stages will be intermingled on a leaf.',
        treatment:'Growing resistant varieties is the best and most economical method of minimizing rust losses.Leaf rust is effectively controlled by the timely application of foliar fungicides.Fungicides currently registered for leaf rust control on wheat in Nebraska include Quadris (azoxystrobin): Stratego (propiconazole + trifloxystrobin); PropiMax EC and Tilt (propiconazole) and the mancozeb-based products Manzate, Dithane, and Penncozeb.Fungicide application may not always be cost effective if rust severity levels are low or if rust is slow to develop.'
    },
    stem_rust:{
        details:'Stem rust, also known as cereal rust, black rust, red rust or red dust, is caused by the fungus Puccinia graminis, which causes significant disease in cereal crops.',
        symptoms:' Symptoms begin as small circular to oval yellow spots on infected tissue of the upper leaf surface.As the disease progresses, the spots develop into orange-colored pustules that may be surrounded by a yellow halo.The pustules produce a large number of spores that are easily dislodged from the pustule, resulting in an “orange dust” on the leaf surface or on clothes, hands, and equipment.As the disease progresses, black spores may be produced, resulting in a mixture of orange and black lesions on the same leaf.',
        treatment:'Destroying previous wheat plants and volunteer wheat, by tillage or herbicide, is another important step in the prevention of several diseases, including wheat streak mosaic, High Plains virus, barley yellow dwarf, and leaf and stem rusts.Eliminating the “green bridge” between wheat crops will help prevent mechanisms of carryover from one growing season to the next.Crop rotation is also very helpful at reducing disease carryover because many diseases are host-specific and proliferate when the same crop is planted year after year.Most disease cycles can be disrupted by as little as one year of rotation or fallow conditions.'
    },
    diseased_okra_leaf:{
        details:'The yield loss caused by Yellow vein mosaic disease of okra in infected plants ranges between 50 to 90 per cent depending on stage of growth at which infection occurs (Sastry and Singh 1974; Sinha and Chakrabarthi 1978).Viruses belonging to famixly Geminiviride have a single-stranded (ss) circular DNA genomes with characteristic twinned quasi-icosahedral particles (Lazarowitz 1992).These are divided into four genera that are distinguished on the basis of host range, insect vector and genome ar- rangement (Stanley et al.2005).The most important of these are the members of the genus Begomovirus, transmitted exclusively by the whitefly Bemisia tabaci Gennadius.',
        symptoms:'Spots on okra leaves may also be the result of the pathogen Cercospora abelmoschi.Cercospora is a fungal infection wherein spores are carried by the wind from infected plants to other plants.These spores adhere to the leaf surface and grow, becoming mycelia growth.This growth is present on the undersides of the leaves in the form of yellowing and brown spots.As the disease progresses, the leaves become dry and brown.',
        treatment:'Keeping leaf wet for a long time is a major cause of infection primarily through water-splashed spores.Manage overhead irrigation with minimal chances of continued long periods of leaf wetness.If the problem is a continuous one, use protective fungicides before any infection can happen.Fungicide management may be difficult once the symptoms develop.'
    }
}
